package clio.Entities;
// Generated 19-ene-2013 17:19:43 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Conexion generated by hbm2java
 */
public class Conexion  implements java.io.Serializable {

     private String tipoBuscar=" ", termino;
     private int mes=13, anio, cantidad;
    
     public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public String getTipoBuscar() {
        return tipoBuscar;
    }

    public void setTipoBuscar(String tipoBuscar) {
        this.tipoBuscar = tipoBuscar;
    }

    public String getTermino() {
        return termino;
    }

    public void setTermino(String termino) {
        if (this.termino==null) {
            this.termino = " ";
        }
        else {
            this.termino = termino;
        }
    }

    public int getMes() {
        return mes;
    }
    
    public String getMesToString(){
        String mesString;
        switch (mes) {
            case 0: mesString = "Todos_Meses";
                     break;
            case 1:  mesString = "Enero";
                     break;
            case 2:  mesString = "Febrero";
                     break;
            case 3:  mesString = "Marzo";
                     break;
            case 4:  mesString = "Abril";
                     break;
            case 5:  mesString = "Mayo";
                     break;
            case 6:  mesString = "Junio";
                     break;
            case 7:  mesString = "Julio";
                     break;
            case 8:  mesString = "Agosto";
                     break;
            case 9:  mesString = "Septiembre";
                     break;
            case 10: mesString = "Octubre";
                     break;
            case 11: mesString = "Noviembre";
                     break;
            case 12: mesString = "Diciembre";
                     break;
            default: mesString = " ";
                     break;
        }
        return mesString;
    }

    public void setMes(int mes) {
        this.mes = mes;
    }

    public int getAnio() {
        return anio;
    }

    public void setAnio(int anio) {
        this.anio = anio;
    }
    
     private Long coId;
     private Usuario usuario;
     private Pc pc;
     private Date inicio;
     private Date fin;
    
    public Conexion() {
    }
    
    public Conexion(int cantidad,int mes) {
        this.mes = mes;
        this.cantidad = cantidad;
    }
    
    public Conexion(Usuario usuario, Pc pc, Date inicio, Date fin) {
       this.usuario = usuario;
       this.pc = pc;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public Long getCoId() {
        return this.coId;
    }
    
    public void setCoId(Long coId) {
        this.coId = coId;
    }
    
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    public Pc getPc() {
        return this.pc;
    }
    
    public void setPc(Pc pc) {
        this.pc = pc;
    }
    
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
}