package clio.Entities;
// Generated 21-ene-2013 0:34:55 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio implements java.io.Serializable {

    private Long labId;
    private String labNombre;
    private String labDescripcion;
    private String labMascarasubred;
    private String labPuertaenlace;
    private String labDnspreferido;
    private String labDnsalternativo1;
    private String labDnsalternativo2;
    private Integer labCantFila;
    private Integer labCantColumna;
    private String labEstado;
    private Long labTiempoUso;
    private Set<Pc> pcs = new HashSet<Pc>(0);

    public Laboratorio() {
    }

    public Laboratorio(String labNombre, String labDescripcion, String labMascarasubred, String labPuertaenlace, String labDnspreferido, String labDnsalternativo1, String labDnsalternativo2, Integer labCantFila, Integer labCantColumna, String labEstado, Long labTiempoUso, Set<Pc> pcs) {
        this.labNombre = labNombre;
        this.labDescripcion = labDescripcion;
        this.labMascarasubred = labMascarasubred;
        this.labPuertaenlace = labPuertaenlace;
        this.labDnspreferido = labDnspreferido;
        this.labDnsalternativo1 = labDnsalternativo1;
        this.labDnsalternativo2 = labDnsalternativo2;
        this.labCantFila = labCantFila;
        this.labCantColumna = labCantColumna;
        this.labEstado = labEstado;
        this.labTiempoUso = labTiempoUso;
        this.pcs = pcs;
    }

    public Long getLabId() {
        return this.labId;
    }

    public void setLabId(Long labId) {
        this.labId = labId;
    }

    public String getLabNombre() {
        return this.labNombre;
    }

    public void setLabNombre(String labNombre) {
        this.labNombre = labNombre;
    }

    public String getLabDescripcion() {
        return this.labDescripcion;
    }

    public void setLabDescripcion(String labDescripcion) {
        this.labDescripcion = labDescripcion;
    }

    public String getLabMascarasubred() {
        return this.labMascarasubred;
    }

    public void setLabMascarasubred(String labMascarasubred) {
        this.labMascarasubred = labMascarasubred;
    }

    public String getLabPuertaenlace() {
        return this.labPuertaenlace;
    }

    public void setLabPuertaenlace(String labPuertaenlace) {
        this.labPuertaenlace = labPuertaenlace;
    }

    public String getLabDnspreferido() {
        return this.labDnspreferido;
    }

    public void setLabDnspreferido(String labDnspreferido) {
        this.labDnspreferido = labDnspreferido;
    }

    public String getLabDnsalternativo1() {
        return this.labDnsalternativo1;
    }

    public void setLabDnsalternativo1(String labDnsalternativo1) {
        this.labDnsalternativo1 = labDnsalternativo1;
    }

    public String getLabDnsalternativo2() {
        return this.labDnsalternativo2;
    }

    public void setLabDnsalternativo2(String labDnsalternativo2) {
        this.labDnsalternativo2 = labDnsalternativo2;
    }

    public Integer getLabCantFila() {
        return this.labCantFila;
    }

    public void setLabCantFila(Integer labCantFila) {
        this.labCantFila = labCantFila;
    }

    public Integer getLabCantColumna() {
        return this.labCantColumna;
    }

    public void setLabCantColumna(Integer labCantColumna) {
        this.labCantColumna = labCantColumna;
    }

    public String getLabEstado() {
        return this.labEstado;
    }

    public void setLabEstado(String labEstado) {
        this.labEstado = labEstado;
    }

    public Long getLabTiempoUso() {
        return this.labTiempoUso;
    }

    public void setLabTiempoUso(Long labTiempoUso) {
        this.labTiempoUso = labTiempoUso;
    }

    public Set<Pc> getPcs() {
        return this.pcs;
    }

    public void setPcs(Set<Pc> pcs) {
        this.pcs = pcs;
    }

    @Override
    public String toString() {
        return labNombre;
    }
}
