package clio.Entities;
// Generated 21-ene-2013 22:10:24 by Hibernate Tools 3.2.1.GA



/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private Integer modId;
     private String modNombre;
     private String modDescripcion;
     private String modEstado;

    public Modulo() {
    }

    public Modulo(String modNombre, String modDescripcion, String modEstado) {
       this.modNombre = modNombre;
       this.modDescripcion = modDescripcion;
       this.modEstado = modEstado;
    }
   
    public Integer getModId() {
        return this.modId;
    }
    
    public void setModId(Integer modId) {
        this.modId = modId;
    }
    public String getModNombre() {
        return this.modNombre;
    }
    
    public void setModNombre(String modNombre) {
        this.modNombre = modNombre;
    }
    public String getModDescripcion() {
        return this.modDescripcion;
    }
    
    public void setModDescripcion(String modDescripcion) {
        this.modDescripcion = modDescripcion;
    }
    public String getModEstado() {
        return this.modEstado;
    }
    
    public void setModEstado(String modEstado) {
        this.modEstado = modEstado;
    }




}


