package clio.Entities;
// Generated 21-ene-2013 22:10:24 by Hibernate Tools 3.2.1.GA



/**
 * RolesUsuarios generated by hbm2java
 */
public class RolesUsuarios  implements java.io.Serializable {


     private Long ruId;
     private Usuario usuario;
     private String ruAuthority;

    public RolesUsuarios() {
    }

    public RolesUsuarios(Usuario usuario, String ruAuthority) {
       this.usuario = usuario;
       this.ruAuthority = ruAuthority;
    }
   
    public Long getRuId() {
        return this.ruId;
    }
    
    public void setRuId(Long ruId) {
        this.ruId = ruId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRuAuthority() {
        return this.ruAuthority;
    }
    
    public void setRuAuthority(String ruAuthority) {
        this.ruAuthority = ruAuthority;
    }




}


