package clio.Entities;
// Generated 21-ene-2013 0:34:55 by Hibernate Tools 3.2.1.GA


import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Sanciones generated by hbm2java
 */
public class Sanciones  implements java.io.Serializable {


     private Long saId;
     private Usuario usuario;
     private Date saDesde;
     private Date saHasta;
     private String saMotivo;
     private String saObservaciones;
     private String saVigencia;

    public Sanciones() {
    }

    public Sanciones(Usuario usuario, Date saDesde, Date saHasta, String saMotivo, String saObservaciones, String saVigencia) {
       this.usuario = usuario;
       this.saDesde = saDesde;
       this.saHasta = saHasta;
       this.saMotivo = saMotivo;
       this.saObservaciones = saObservaciones;
       this.saVigencia = saVigencia;
    }
   
    public Long getSaId() {
        return this.saId;
    }
    
    public void setSaId(Long saId) {
        this.saId = saId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getSaDesde() {
        return this.saDesde;
    }
    
    public void setSaDesde(Date saDesde) {
        this.saDesde = saDesde;
    }
    public Date getSaHasta() {
        return this.saHasta;
    }
    
    public void setSaHasta(Date saHasta) {
        this.saHasta = saHasta;
    }
    public String getSaMotivo() {
        return this.saMotivo;
    }
    
    public void setSaMotivo(String saMotivo) {
        this.saMotivo = saMotivo;
    }
    public String getSaObservaciones() {
        return this.saObservaciones;
    }
    
    public void setSaObservaciones(String saObservaciones) {
        this.saObservaciones = saObservaciones;
    }
    public String getSaVigencia() {
        return this.saVigencia;
    }
    
    public void setSaVigencia(String saVigencia) {
        this.saVigencia = saVigencia;
    }


    public String fechaDesde(){
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/YYYY"); 
        return format.format(saDesde); 
    }

    public String fechaHasta(){
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/YYYY"); 
        return format.format(saHasta); 
    }

}


