package clio.Entities;
// Generated 21-ene-2013 0:34:55 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long usId;
     private String usNombres;
     private String usApellidos;
     private String usEmail;
     private String usFacultad;
     private String usUsername;
     private String usEnabled;
     private String usCedula;
     private String usPassword;
     private String usMatricula;
     private Set<Sanciones> sancioneses = new HashSet<Sanciones>(0);
     private Set<RolesUsuarios> rolesUsuarioses = new HashSet<RolesUsuarios>(0);
     private Set<Conexion> conexions = new HashSet<Conexion>(0);
  

    public Usuario() {
    }

    public Usuario(String usNombres, String usApellidos, String usEmail, String usFacultad, String usUsername, String usEnabled, String usCedula, String usPassword, String usMatricula, Set<Sanciones> sancioneses, Set<RolesUsuarios> rolesUsuarioses, Set<Conexion> conexions) {
       this.usNombres = usNombres;
       this.usApellidos = usApellidos;
       this.usEmail = usEmail;
       this.usFacultad = usFacultad;
       this.usUsername = usUsername;
       this.usEnabled = usEnabled;
       this.usCedula = usCedula;
       this.usPassword = usPassword;
       this.usMatricula = usMatricula;
       this.sancioneses = sancioneses;
       this.rolesUsuarioses = rolesUsuarioses;
       this.conexions = conexions;
    }
   
    public Long getUsId() {
        return this.usId;
    }
    
    public void setUsId(Long usId) {
        this.usId = usId;
    }
    public String getUsNombres() {
        return this.usNombres;
    }
    
    public void setUsNombres(String usNombres) {
        this.usNombres = usNombres;
    }
    public String getUsApellidos() {
        return this.usApellidos;
    }
    
    public void setUsApellidos(String usApellidos) {
        this.usApellidos = usApellidos;
    }
    public String getUsEmail() {
        return this.usEmail;
    }
    
    public void setUsEmail(String usEmail) {
        this.usEmail = usEmail;
    }
    public String getUsFacultad() {
        return this.usFacultad;
    }
    
    public void setUsFacultad(String usFacultad) {
        this.usFacultad = usFacultad;
    }
    public String getUsUsername() {
        return this.usUsername;
    }
    
    public void setUsUsername(String usUsername) {
        this.usUsername = usUsername;
    }
    public String getUsEnabled() {
        return this.usEnabled;
    }
    
    public void setUsEnabled(String usEnabled) {
        this.usEnabled = usEnabled;
    }
    public String getUsCedula() {
        return this.usCedula;
    }
    
    public void setUsCedula(String usCedula) {
        this.usCedula = usCedula;
    }
    public String getUsPassword() {
        return this.usPassword;
    }
    
    public void setUsPassword(String usPassword) {
        this.usPassword = usPassword;
    }
    public String getUsMatricula() {
        return this.usMatricula;
    }
    
    public void setUsMatricula(String usMatricula) {
        this.usMatricula = usMatricula;
    }
    public Set<Sanciones> getSancioneses() {
        return this.sancioneses;
    }
    
    public void setSancioneses(Set<Sanciones> sancioneses) {
        this.sancioneses = sancioneses;
    }
    public Set<RolesUsuarios> getRolesUsuarioses() {
        return this.rolesUsuarioses;
    }
    
    public void setRolesUsuarioses(Set<RolesUsuarios> rolesUsuarioses) {
        this.rolesUsuarioses = rolesUsuarioses;
    }
    public Set<Conexion> getConexions() {
        return this.conexions;
    }
    
    public void setConexions(Set<Conexion> conexions) {
        this.conexions = conexions;
    }

    @Override
    public String toString()
    {
        return usApellidos+" "+usNombres;
    }
}


